### ISSUE TITLE
As a developer, I want to integrate open weather API, so I can get weather data on my app

### ISSUE THREAD

**Issue by osewemwai** [osewemwai/dalili#5]
### Tasks
- [ ] Get api credentials
- [ ] Create data models classes
- [ ] Create data fetch class

### Acceptance Criteria
- [ ] Get json data loaded in console
