### ISSUE TITLE
As a user I want to use the map so that I would get the weather by location selected on the map.

### ISSUE THREAD

**Issue by osewemwai** [osewemwai/dalili#7]
###Tasks
- [ ] #10
- [ ] #11
- [ ] #12
- [ ] #13

### Acceptance Criteria

- [ ] User can enter a location by typing
- [ ] User can load current locations
- [ ] Load whether data of user entered location
