### ISSUE TITLE
As a user I want to get whether forecast by time intervals so that I can plan myself for coming seasons

### ISSUE THREAD

**Issue by osewemwai** [osewemwai/dalili#8]
### Tasks

- [ ] Implement a weather forecast screen
- [ ] Implement date range selector by Week, Month and Year

### Acceptance Criteria

- [ ] View weather by forecast
